init: depend on libselinux
In file included from device/motorola/surnia/init/init_surnia.cpp
system/core/init/util.h:29:10: fatal error: 'selinux/label.h' file not found

Change-Id: Id27b13647465e03a9131e385876e0cf655baccca

Conflicts:
	init/Android.mk